# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Simcoes
tagline:          'An archive of the Simcoes' blog.'
description:      'Here is a record of our lives from 2010–2016. Enjoy! 😜'
url:              http://archive.thesimcoes.net
baseurl:          /

author:
  name:           'Jonathan Simcoe'
  url:            https://jdsimcoe.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jdsimcoe/archive.thesimcoes.net
