# Permalinks
permalink:        pretty

# Setup
title:            The Simcoes
tagline:          'An archive for the Simcoe blog.'
description:      'Here is a record of our lives from 2010–2016. Enjoy! 😜'
url:              http://archive.thesimcoes.net

author:
  name:           'Jonathan Simcoe'
  url:            https://jdsimcoe.com

paginate:         20

# Custom vars
version:          2.1.0

# Gems
gems:
- jekyll-paginate
- jekyll-watch

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
